[build]
  dockerfilePath = "Dockerfile.dev"

[deploy]
  startCommand = "cp /app/var/docker/nginx.railway.conf /etc/nginx/nginx.conf && nginx -t && echo 'nginx config ok' && nginx && echo 'nginx started' && pnpm run pm2"
